### ISSUE TITLE
How do you whitelist attribute selectors in email-comb?

### ISSUE THREAD

**Issue by cossssmin** [codsen/codsen#27]
**Package's name**

`email-comb`

**Describe the situation**

How do I prevent it from removing this CSS?

```css
@media (max-width: 600px) {
    [data-ogsc] .sm-text-red-500 {
        color: #ef4444;
    }
}
```
